import { defineConfig } from 'vite';
import { resolve } from 'path';
import { readFileSync } from 'fs';

const pkg = JSON.parse(readFileSync('./package.json', 'utf-8'));

// Builds the Home Assistant panel preview: the real renderer running in an
// iframe served by the companion integration. preview/preview.html is
// generated by scripts/build-panel.cjs from index.html's widget skeleton.
export default defineConfig({
  root: resolve(__dirname, 'preview'),
  base: './',
  build: {
    outDir: resolve(__dirname, 'dist-panel'),
    emptyOutDir: true,
    rollupOptions: {
      input: resolve(__dirname, 'preview', 'preview.html'),
    },
    target: 'es2022',
    minify: true,
    sourcemap: false,
    // Emit every asset as a file, never a data: URI. The HA companion
    // integration serves this panel under a font-src 'self' CSP, which blocks
    // inlined fonts outright; Vite's 4 KB default would quietly inline the
    // smaller woff2 subsets.
    assetsInlineLimit: 0,
  },
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  resolve: {
    alias: {
      // The preview must never contain development fixtures.
      '@dev-climate-demo': resolve(__dirname, 'src/dev-climate-demo.production.js'),
      '@': resolve(__dirname, 'src'),
      '@hadw/renderer': resolve(__dirname, 'packages/widget-renderer/src'),
      events: 'events',
      'hls.js': 'hls.js/dist/hls.light.mjs',
    },
  },
});
