#!/usr/bin/env node
/**
 * Build the Home Assistant panel preview bundle.
 *
 * The preview page runs the real renderer (ui.js and friends) inside an
 * iframe, so its markup must be the same widget skeleton the desktop uses.
 * To prevent drift, the skeleton is extracted from index.html at build time
 * rather than maintained as a copy.
 *
 * Usage:
 *   node scripts/build-panel.cjs [--copy-to <companion frontend dir>]
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

function resolveViteCli() {
  const packageJsonPath = require.resolve('vite/package.json');
  const vitePackage = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
  const viteBin = typeof vitePackage.bin === 'string' ? vitePackage.bin : vitePackage.bin?.vite;

  if (!viteBin) throw new Error('Could not resolve the Vite CLI from vite/package.json');

  const viteCli = path.resolve(path.dirname(packageJsonPath), viteBin);
  if (!fs.existsSync(viteCli)) throw new Error(`Vite CLI not found at ${viteCli}`);
  return viteCli;
}

function extractWidgetSkeleton(indexHtml) {
  // The full body ships so the widget's real settings modal (and every other
  // modal ui.js/settings.js expect) exists in the preview; scripts are
  // stripped because the preview has its own bootstrap.
  const match = indexHtml.match(/<body[^>]*>([\s\S]*)<\/body>/);
  if (!match) throw new Error('body not found in index.html');
  return match[1].replace(/<script[\s\S]*?<\/script>/g, '');
}

function buildPreviewHtml() {
  const indexHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const skeleton = extractWidgetSkeleton(indexHtml);
  return `<!doctype html>
<!-- GENERATED by scripts/build-panel.cjs — do not edit. The widget skeleton is
     extracted from index.html so the preview and the desktop cannot drift. -->
<html>
  <head>
    <meta charset="UTF-8" />
    <title>HA Desktop Widget preview</title>
  </head>
  <body class="hadw-preview">
${skeleton}
    <script type="module" src="./preview-main.js"></script>
  </body>
</html>
`;
}

function main() {
  const args = process.argv.slice(2);
  const copyToIndex = args.indexOf('--copy-to');
  const copyTo = copyToIndex !== -1 ? args[copyToIndex + 1] : null;

  fs.writeFileSync(path.join(ROOT, 'preview', 'preview.html'), buildPreviewHtml());
  execFileSync(process.execPath, [resolveViteCli(), 'build', '--config', 'vite.panel.config.js'], {
    cwd: ROOT,
    stdio: 'inherit',
  });

  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  let sourceCommit = 'unknown';
  try {
    sourceCommit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT }).toString().trim();
  } catch {
    /* not a git checkout */
  }
  const stamp = { version: pkg.version, sourceCommit };
  fs.writeFileSync(
    path.join(ROOT, 'dist-panel', 'PANEL_VERSION.json'),
    `${JSON.stringify(stamp, null, 2)}\n`
  );

  if (copyTo) {
    const target = path.resolve(copyTo, 'preview');
    fs.rmSync(target, { recursive: true, force: true });
    fs.cpSync(path.join(ROOT, 'dist-panel'), target, { recursive: true });
    console.log(`Panel preview copied to ${target}`);
  }
  console.log(`Panel preview built (version ${stamp.version}, ${sourceCommit.slice(0, 9)})`);
}

if (require.main === module) main();

module.exports = { buildPreviewHtml, extractWidgetSkeleton, resolveViteCli };
