#!/usr/bin/env node
/**
 * Build the Home Assistant panel preview bundle.
 *
 * The preview page runs the real renderer (ui.js and friends) inside an
 * iframe, so its markup must be the same widget skeleton the desktop uses.
 * To prevent drift, the skeleton is extracted from index.html at build time
 * rather than maintained as a copy.
 *
 * Usage:
 *   node scripts/build-panel.cjs [--copy-to <companion frontend dir>]
 */

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

function extractWidgetSkeleton(indexHtml) {
  const lines = indexHtml.split('\n');
  const start = lines.findIndex((line) => line.includes('class="widget-content"'));
  if (start === -1) throw new Error('widget-content block not found in index.html');
  let depth = 0;
  for (let i = start; i < lines.length; i += 1) {
    depth += (lines[i].match(/<div\b/g) || []).length;
    depth -= (lines[i].match(/<\/div>/g) || []).length;
    if (depth === 0 && i > start) {
      return lines.slice(start, i + 1).join('\n');
    }
  }
  throw new Error('widget-content block not closed in index.html');
}

function buildPreviewHtml() {
  const indexHtml = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const skeleton = extractWidgetSkeleton(indexHtml);
  return `<!doctype html>
<!-- GENERATED by scripts/build-panel.cjs — do not edit. The widget skeleton is
     extracted from index.html so the preview and the desktop cannot drift. -->
<html>
  <head>
    <meta charset="UTF-8" />
    <title>HA Desktop Widget preview</title>
  </head>
  <body class="hadw-preview">
${skeleton}
    <script type="module" src="./preview-main.js"></script>
  </body>
</html>
`;
}

function main() {
  const args = process.argv.slice(2);
  const copyToIndex = args.indexOf('--copy-to');
  const copyTo = copyToIndex !== -1 ? args[copyToIndex + 1] : null;

  fs.writeFileSync(path.join(ROOT, 'preview', 'preview.html'), buildPreviewHtml());
  execFileSync('npx', ['vite', 'build', '--config', 'vite.panel.config.js'], {
    cwd: ROOT,
    stdio: 'inherit',
  });

  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  let sourceCommit = 'unknown';
  try {
    sourceCommit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT }).toString().trim();
  } catch {
    /* not a git checkout */
  }
  const stamp = { version: pkg.version, sourceCommit };
  fs.writeFileSync(
    path.join(ROOT, 'dist-panel', 'PANEL_VERSION.json'),
    `${JSON.stringify(stamp, null, 2)}\n`
  );

  if (copyTo) {
    const target = path.resolve(copyTo, 'preview');
    fs.rmSync(target, { recursive: true, force: true });
    fs.cpSync(path.join(ROOT, 'dist-panel'), target, { recursive: true });
    console.log(`Panel preview copied to ${target}`);
  }
  console.log(`Panel preview built (version ${stamp.version}, ${sourceCommit.slice(0, 9)})`);
}

if (require.main === module) main();

module.exports = { buildPreviewHtml, extractWidgetSkeleton };
